Added of method, for kafka producers
ESIR-SI-2020/DomainAndDatabases pull request #9
Opened 2019-12-02 09:26 UTC by corentinduchatelet

this method is needed for our project CommandsHandler

2020-01-12 17:53 UTC, AntoineCheron requested changes

2020-01-12 17:53 UTC, AntoineCheron commented on domain/src/main/java/fr/esir/jxc/domain/events/Event.java
> +        return Optional.of(new Event(UUID.randomUUID().toString(), event.getClass().getSimpleName(), Json.MAPPER.createObjectNode().putPOJO("event", event), LocalDateTime.of(currentDate, currentTime)
```suggestion
        return Optional.of(new Event(UUID.randomUUID().toString(), event.getClass().getSimpleName(), Json.MAPPER.createObjectNode().putPOJO("event", event), LocalDateTime.now()));
```

2020-01-12 17:53 UTC, AntoineCheron commented on domain/src/main/java/fr/esir/jxc/domain/events/Event.java
> +        LocalTime currentTime = LocalTime.now();
Il existe `LocalDateTime.now()` , vous pouvez donc supprimer ces deux lignes

2020-01-13 09:12 UTC, corentinduchatelet reviewed
review validée

2020-01-13 09:13 UTC, merged